extern int64_t scan_msg_rate_hz;
extern int64_t cfg_min_scan_rate;
extern int64_t scan_observed_reliability;
extern int64_t cfg_expected_scan_reliability;
extern int64_t map_server_state;
extern int64_t cfg_active_state;
extern int64_t bridge_param_change_count;
extern int64_t scan_subscriber_count;
extern int64_t cfg_expected_scan_subscribers;
extern int64_t odom_subscriber_count;
extern int64_t cfg_expected_odom_subscribers;
extern int64_t attacker_creds_count;
extern int64_t unauth_node_count;
extern int64_t attacker_net_admin_count;
extern int64_t drive_publisher_count;
extern int64_t cfg_expected_drive_publishers;
extern int64_t drive_msg_rate_hz;
extern int64_t cfg_max_drive_rate;
extern float drive_speed_abs;
extern float cfg_max_safe_speed;
extern float drive_steering_abs;
extern float cfg_max_safe_steering;
extern int64_t scan_invalid_count;
extern int64_t cfg_max_scan_invalid_count;
extern int64_t scan_zero_count;
extern int64_t cfg_max_scan_zero_count;
extern float scan_range_spread;
extern float cfg_min_scan_range_spread;
extern int64_t scan_publisher_count;
extern int64_t cfg_expected_scan_publishers;
extern float scan_stamp_age_sec;
extern float cfg_max_scan_stamp_age_sec;
void handlerREQ_scan_unreliable(void);
void handlerREQ_map_server_down(void);
void handlerREQ_bridge_misconfigured(void);
void handlerREQ_data_leaked(void);
void handlerREQ_credential_access(void);
void handlerREQ_can_join_ros_graph(void);
void handlerREQ_can_net_admin(void);
void handlerREQ_drive_DoS(void);
void handlerREQ_command_unsafe(void);
void handlerREQ_scan_corrupted(void);
void step(void);
