extern int64_t scan_invalid_count;
extern int64_t cfg_max_scan_invalid_count;
extern int64_t scan_zero_count;
extern int64_t cfg_max_scan_zero_count;
extern bool scan_all_same;
extern int64_t scan_observed_reliability;
extern int64_t cfg_expected_scan_reliability;
extern float scan_last_msg_time_sec;
extern float scan_prev_msg_time_sec;
extern float cfg_max_scan_interarrival_sec;
extern float current_time_sec;
extern float cfg_scan_timeout_sec;
extern bool scan_pub_event;
extern int64_t scan_pub_id;
extern int64_t cfg_allowed_scan_pub_id;
extern bool scan_sub_event;
extern int64_t scan_sub_id;
extern int64_t cfg_allowed_scan_sub_id;
extern bool drive_pub_event;
extern int64_t drive_pub_id;
extern int64_t cfg_allowed_drive_pub_id;
extern float drive_last_msg_time_sec;
extern float drive_prev_msg_time_sec;
extern float cfg_min_drive_interarrival_sec;
extern bool bridge_param_event;
extern int64_t bridge_param_name_id;
extern int64_t cfg_allowed_bridge_param_name_id;
extern bool map_lifecycle_event;
extern int64_t map_transition_id;
extern int64_t cfg_allowed_map_transition_id;
void handlerREQ_scan_invalid_attack(void);
void handlerREQ_scan_zero_attack(void);
void handlerREQ_scan_uniform_attack(void);
void handlerREQ_scan_qos_attack(void);
void handlerREQ_scan_delay_attack(void);
void handlerREQ_scan_drop_attack(void);
void handlerREQ_scan_publisher_attack(void);
void handlerREQ_scan_reader_attack(void);
void handlerREQ_drive_publisher_attack(void);
void handlerREQ_drive_flood_attack(void);
void handlerREQ_bridge_param_attack(void);
void handlerREQ_map_lifecycle_attack(void);
void step(void);
